apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jinli-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: jinli-device-plugin
  template:
    metadata:
      labels:
        name: jinli-device-plugin
    spec:
      runtimeClassName: nvidia
      containers:
      - image: jinli.harbor.com/jinlik8s-device/jinli-device-plugin:v1.2.1
        name: device
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: kubelet
          mountPath: /var/lib/kubelet/device-plugins
        - name: vgpu
          mountPath: /srv
        - name: tmp
          mountPath: /tmp
        - name: localtime
          mountPath: /etc/localtime
        - name: cdi
          mountPath: /var/run/cdi
        command:
        - "sh"
        - "-c"
        - "cp -r /usr/local/jinli/* /srv && /app/device-plugin"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        #- name: NVIDIA_MIG_MONITOR_DEVICES
        #  value: all
      volumes:
      - name: kubelet
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: vgpu
        hostPath:
          path: /usr/local/jinli
      - name: tmp
        hostPath:
          path: /tmp
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: cdi
        hostPath:
          path: /var/run/cdi
