apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jinli-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: jinli-device-plugin
  template:
    metadata:
      labels:
        name: jinli-device-plugin
    spec:
      containers:
      - image: jinli.harbor.com/jinlik8s-device/jinli-device-plugin:v1.0.1
        name: device
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: kubelet
          mountPath: /var/lib/kubelet/device-plugins
        - name: vgpu
          mountPath: /uar/local/jinli
        - name: tmp
          mountPath: /tmp
        - name: localtime
          mountPath: /etc/localtime
        command:
        - "/app/device-plugin"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
            fieldPath: spec.nodeName
        - name: NVIDIA_MIG_MONITOR_DEVICES
          value: all
      volumes:
      - name: kubelet
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: vgpu
        hostPath:
          path: /usr/local/jinli
      - name: tmp
        hostPath:
          path: /tmp
      - name: localtime
        hostPath:
          path: /etc/localtime
