apiVersion: v1
kind: Pod
metadata:
  name: jinli-gpu
spec:
  schedulerName: jinli-scheduler
  containers:
  - name: gpu-container
    image: jinli.harbor.com/jinlik8s-device/app:v1.2.1
    command: ["sh", "-c", "tail -f /dev/null"]
    env:
    - name: GPUCORES
      value: 20
    - name: GPUMEM
      value: 200
    - name: THRESHOLD
      value: 1e-6
    resources:
      limits:
        jinli.io/gpu: 1